### PR TITLE
Created CLI ulitity

### PR DESCRIPTION
**Pull request by krisclarkdev**
Modified your code to be a CLI utility.  Added myself as one of the authors in package.json

### CODE REVIEW

**Comment by krisclarkdev** [comment]
Removed test code for future features

**Comment by krisclarkdev** [comment]
Fixed errors keeping me from getting the wrong passphrase

**Comment by kantium** [comment]
@kclark-jenkins Thanks you very much by the way

**Comment by krisclarkdev** [comment]
No problem, man.  Happy to help.

**Comment by krisclarkdev** [comment]
BTW, I added this to NPM.  Let me know if you've got an account and I'll add you to the project.

**Pull request merged**
